# Generated by Django 3.2.16 on 2023-04-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('nom_ing', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('type_ing', models.CharField(max_length=150)),
                ('nature', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Levain',
            fields=[
                ('code_levain', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('type_levain', models.CharField(choices=[('F', 'Frais'), ('L', 'Liquide'), ('Lyo', 'Lyophilisé'), ('S', 'Séché')], max_length=3)),
                ('date', models.DateField()),
                ('pH', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('att', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
            ],
            options={
                'verbose_name': 'Levain',
                'db_table': 'levain',
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('nom_parametre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('unite', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Parametre',
                'verbose_name_plural': 'Parametre',
                'db_table': 'Parametre',
            },
        ),
        migrations.CreateModel(
            name='TechniquePanification',
            fields=[
                ('nom_tech', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TechniquePanification',
                'verbose_name_plural': 'TechniquePanifications',
                'db_table': 'Technique_Panification',
            },
        ),
        migrations.CreateModel(
            name='TechniqueRafraichissement',
            fields=[
                ('nom_tech', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TechniqueRafraichissement',
                'verbose_name_plural': 'TechniqueRafraichissements',
                'db_table': 'Technique_Rafraichissement',
            },
        ),
        migrations.CreateModel(
            name='Rafraichissement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_rafraichissement', models.DateField()),
                ('num_rafraichit', models.IntegerField()),
                ('nom_ing', models.CharField(max_length=150)),
                ('masse_ing', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('levain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.levain')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techniquerafraichissement')),
            ],
            options={
                'verbose_name': 'Rafraichissement',
                'verbose_name_plural': 'Rafraichissements',
                'db_table': 'Rafraichissement',
            },
        ),
        migrations.CreateModel(
            name='Panification',
            fields=[
                ('num_test', models.IntegerField(primary_key=True, serialize=False)),
                ('date_panification', models.DateField()),
                ('num_repetition', models.IntegerField()),
                ('apport', models.DecimalField(decimal_places=1, default=0, max_digits=50)),
                ('levain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.levain')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techniquepanification')),
            ],
            options={
                'verbose_name': 'Panification',
                'verbose_name_plural': 'Panifications',
                'db_table': 'test_panification',
            },
        ),
        migrations.CreateModel(
            name='CompositionPanification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_ing', models.CharField(max_length=150)),
                ('masse_ing', models.DecimalField(decimal_places=2, max_digits=50)),
                ('panification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.panification')),
            ],
            options={
                'verbose_name': 'CompositionPanification',
                'verbose_name_plural': 'CompositionPanifications',
                'db_table': 'Composition_Panification',
            },
        ),
        migrations.CreateModel(
            name='CompositionLevain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_ing', models.CharField(max_length=150)),
                ('masse_ing', models.DecimalField(decimal_places=2, max_digits=50)),
                ('levain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.levain')),
            ],
            options={
                'verbose_name': 'CompositionLevain',
                'verbose_name_plural': 'CompositionLevains',
                'db_table': 'Composition_Levain',
            },
        ),
        migrations.CreateModel(
            name='CaracterisationPanification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_parametre', models.CharField(max_length=150)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=50)),
                ('panification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.panification')),
            ],
            options={
                'verbose_name': 'CaracterisationPanification',
                'verbose_name_plural': 'CaracterisationPanifications',
                'db_table': 'Caracterisation_Panification',
            },
        ),
        migrations.CreateModel(
            name='CaracterisationLevain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_caracterisation', models.DateField()),
                ('num_rep', models.IntegerField()),
                ('nom_parametre', models.CharField(max_length=150)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=50)),
                ('levain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.levain')),
            ],
            options={
                'verbose_name': 'CaracterisationLevain',
                'verbose_name_plural': 'CaracterisationLevain',
                'db_table': 'Caracterisation_Levain',
            },
        ),
    ]
