# Generated by Django 3.2.16 on 2023-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterisationpanification',
            name='heure_panification',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
