# Generated by Django 3.2.16 on 2023-07-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_caracterisationpanification_heure_panification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterisationpanification',
            name='valeur',
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
        migrations.CreateModel(
            name='CaracterPanification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_caracterisation', models.DateField()),
                ('num_rep', models.IntegerField(blank=True, null=True)),
                ('nom_parametre', models.CharField(max_length=150)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=50)),
                ('panification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.panification')),
            ],
            options={
                'verbose_name': 'Caracter_Panification',
                'verbose_name_plural': 'Caracter_Panification',
                'db_table': 'Caracter_Panification',
            },
        ),
    ]
