# Generated by Django 3.2.16 on 2023-07-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230712_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterisationpanification',
            name='valeur',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
