# Generated by Django 3.2.16 on 2023-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_caracterisationpanification_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='panification',
            name='donnees_fin_panif',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='caracterpanification',
            name='date_caracterisation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracterpanification',
            name='nom_parametre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='caracterpanification',
            name='valeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
