# Generated by Django 3.2.16 on 2023-07-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230714_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panification',
            name='donnees_fin_panif',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
