# Generated by Django 3.2.16 on 2023-07-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_panification_donnees_fin_panif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nature',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type_ing',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
