# Generated by Django 3.2.16 on 2023-07-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230715_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='unite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
