# Generated by Django 3.2.16 on 2023-07-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_parametre_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracterpanification',
            name='date_caracterisation',
        ),
        migrations.RemoveField(
            model_name='caracterpanification',
            name='num_rep',
        ),
    ]
