# Generated by Django 3.2.16 on 2023-07-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20230715_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracterisationpanification',
            name='valeur',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True),
        ),
    ]
