# Generated by Django 3.2.16 on 2023-07-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_caracterisationpanification_valeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panification',
            name='donnees_fin_panif',
        ),
        migrations.AddField(
            model_name='panification',
            name='temps_fin_panif',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True),
        ),
    ]
